### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by yoanlcq** [jpernst/emscripten#4]
Currently, tests as run with `python tests/runner.py interactive.test_openal_*` don't pass (I didn't go through each of them at a time though).  
Since they used to pass (on the original Emscripten repo), I think this is because this OpenAL rewrite is still in progress. However, I'd like to make sure that this is currently acknowledged, and not just me.

In any case, what's the plan for fixing them (any prerequisites) ?
  
  
For information, this is what I got:

With `test_openal_animated_looped_pitched_playback` :
```
exception thrown: Assertion failed: val == size - offset, at: /tmp/emscripten_test_interactive_RgPa6o/openal_playback.cpp,173,main
```
With both `test_openal_buffers` and `test_openal_buffers_animated_pitch`:
```
exception thrown: TypeError: Cannot read property '0' of undefined,TypeError: Cannot read property '0' of undefined
    at _alSourceQueueBuffers (http://localhost:8888/test.js:7340:33)
    at _main (http://localhost:8888/test.js:8077:3)
```

**Comment by jpernst** [comment]
I've wrapped up the first round of extensions I wanted to add, so I'll start looking into tests now. Thanks for the heads up.

**Comment by yoanlcq** [comment]
Thanks ! Just to let you know, this is not preventing me from testing capture functions (which I wrote in standalone JS scripts for now), so there's no rush for this in particular.

**Comment by jpernst** [comment]
Ok, I think I've fixed these. Thankfully they were both simple typos.

Also, as it turns out, the animated pitch test actually had a bug in it that just happened to sneak by in the old implementation. It was using a buffer id as a source id, but in the old impl they just so happened to be the same. I've changed it so all IDs are unique now, to catch errors like this, and sure enough it did.
