### ISSUE TITLE
Don't directly use IDs for array indexing

### ISSUE THREAD

**Issue by yoanlcq** [jpernst/emscripten#5]
Since I've noticed that Javascript behaves like this with array indexing : 
```javascript
var a = []; a[42] = "thing"; a
// (43) [undefined × 42, "thing"]
var a = []; a["42"] = "thing"; a
// (43) [undefined × 42, "thing"]
var a = []; a["id42"] = "thing"; a
// [id42: "thing"]
```

Using numeric IDs "as-is" for indexing into arrays looks bad because it allocates cells that are never going to be used, so what I just did in the capture implementation is to always access arrays like this : 
```javascript
var c = AL.captures["id" + deviceId];
```

A bunch of other places in our code could benefit from this change; What do you think ? I'm willing to do it if you agree.

**Comment by jpernst** [comment]
The point of using the numeric IDs is that they can be passed to and from the foreign C or Rust code without having to synthesise them. Also, to avoid allocating unnecessary cells, I use objects `{}` instead of arrays `[]` precisely because the keys are going to be sparse. This makes it effectively a hashmap.

**Comment by yoanlcq** [comment]
I see now ! Didn't know about the `{}` trick (I feel a bit silly because this is part of the basics).  

Also, yes I do pass numeric IDs as expected, but currently only prefix them with "id" at the time of array accesses. Guess I'm gonna have to fix this quick. :)
